"""Pydantic models for event graphs generated by the LLM."""

import uuid
from enum import Enum

from pydantic import BaseModel, Field, model_validator
from pydantic_core import PydanticCustomError
from rdflib import OWL, RDF, RDFS, Graph, Literal, Namespace, URIRef


class BaseEventGraph(BaseModel):
    """Base graph model to represent the graph generated by a LLM from a log event.

    Do not use this class directly in the llm's structured output:
    an ontology-specific subclass should be created using the `build_dynamic_model` function.
    """

    nodes: list
    relationships: list

    def rdflib_graph(
        self,
        namespaces: list[tuple[str, URIRef]],
    ) -> Graph:
        """Convert the generated event graph to a rdflib Graph.

        This method assumes that the nodes and relationships are already in the correct format,
        ontology-compliant, and with valid ids. As such, it does not perform any validation.

        Args:
            namespaces (list[tuple[str, URIRef]]): List of namespace prefixes and their URIs.

        Returns:
            Graph: The rdflib Graph representation of the event graph.

        """
        namespaces_with_default = [*namespaces, ("", URIRef("http://cyberseclab.unibs.it/olx/run/#"))]

        def assign_ns(node_id: str) -> URIRef:
            node_id_split = node_id.split(":")
            node_id_ns = node_id_split[0] if len(node_id_split) > 1 else ""
            node_id_without_ns = node_id_split[1] if len(node_id_split) > 1 else node_id_split[0]

            ns_uri = next((ns[1] for ns in namespaces_with_default if ns[0] == node_id_ns), None)
            if not ns_uri:
                return URIRef(node_id)

            return Namespace(ns_uri)[node_id_without_ns]

        res = Graph()
        for ns in namespaces_with_default:
            res.bind(ns[0], ns[1])

        node_ids_map = {}
        for node in self.nodes:
            node_id = assign_ns(str(uuid.uuid4()))
            node_ids_map[node.id] = node_id

            res.add((node_id, RDF.type, assign_ns(node.type.value)))

            if node.properties:
                for prop in node.properties:
                    res.add((node_id, assign_ns(prop.type.value), Literal(prop.value)))
        for rel in self.relationships:
            start_uri = node_ids_map[rel.source_id]
            end_uri = node_ids_map[rel.target_id]
            res.add((start_uri, assign_ns(rel.type.value), end_uri))

        return res


class _OntologyValidValues:
    """Class to hold the valid values for the ontology."""

    def __init__(self, ontology: Graph):
        self.__ontology = ontology

    @property
    def classes(self) -> list[str]:
        """Return a list of classes URIs (as strings) defined as owl:Class in the ontology."""
        return [
            s.n3(self.__ontology.namespace_manager)
            for s in self.__ontology.subjects(predicate=RDF.type, object=OWL.Class)
        ]

    @property
    def object_properties(self) -> list[str]:
        """Return a list of relationship type URIs (as strings) defined in the ontology."""
        return [
            s.n3(self.__ontology.namespace_manager)
            for s in self.__ontology.subjects(predicate=RDF.type, object=OWL.ObjectProperty)
        ]

    @property
    def type_triples(self) -> list[tuple[str, str, str]]:
        """Return the type definition triples in the ontology."""
        return [
            (
                s.n3(self.__ontology.namespace_manager),
                p.n3(self.__ontology.namespace_manager),
                o.n3(self.__ontology.namespace_manager),
            )
            for s, p, o in self.__ontology.triples((None, None, None))
            if o not in (OWL.Ontology, OWL.AnnotationProperty) and p in (RDF.type, RDFS.subClassOf)
        ]

    @property
    def object_property_triples(self) -> list[tuple[str, str, str]]:
        """Return the object property triples in the ontology."""
        triples: list[tuple[str, str, str]] = []
        for prop_uri, _, _ in self.__ontology.triples((None, RDF.type, OWL.ObjectProperty)):
            domains = list(self.__ontology.objects(prop_uri, RDFS.domain)) or [OWL.Thing]
            ranges = list(self.__ontology.objects(prop_uri, RDFS.range)) or [OWL.Thing]
            prop_n3 = prop_uri.n3(self.__ontology.namespace_manager)
            for d in domains:
                d_n3 = d.n3(self.__ontology.namespace_manager)
                for r in ranges:
                    r_n3 = r.n3(self.__ontology.namespace_manager)
                    triples.append((d_n3, prop_n3, r_n3))
        return triples

    @property
    def data_properties_per_class(self) -> dict[str, list[str]]:
        """Return a mapping of classes to their data properties defined in the ontology."""
        class_data_props: dict[str, list[str]] = {}
        for dataprop_uri, _, _ in self.__ontology.triples((None, RDF.type, OWL.DatatypeProperty)):
            for class_uri in self.__ontology.objects(dataprop_uri, RDFS.domain):
                prop_uri = dataprop_uri.n3(self.__ontology.namespace_manager)
                class_uri_esc = class_uri.n3(self.__ontology.namespace_manager)
                if class_uri_esc not in class_data_props:
                    class_data_props[class_uri_esc] = []
                class_data_props[class_uri_esc].append(prop_uri)
        return class_data_props

    @property
    def data_properties(self) -> list[str]:
        return list(
            {prop for props in self.data_properties_per_class.values() for prop in props},
        )

    @property
    def data_properties_schema(self) -> list[str]:
        return [f"{cls}:{props}" for cls, props in self.data_properties_per_class.items()]


def build_dynamic_model(ontology: Graph) -> type[BaseEventGraph]:
    """Build a dynamic event graph model based on the ontology."""
    valid = _OntologyValidValues(ontology)

    NodeType = Enum("NodeType", {node: node for node in valid.classes}, type=str)  # noqa: N806
    PropertyType = Enum("PropertyType", {prop: prop for prop in valid.data_properties}, type=str)  # noqa: N806
    RelationshipType = Enum("RelationshipType", {rel: rel for rel in valid.object_properties}, type=str)  # noqa: N806

    # Note: The following class names clash with the ones from langchain_neo4j.
    # These names will be passed to the LLM, so it's (probably) better to keep them
    # as clearly named as possible and alias the ones from langchain_neo4j.

    class Property(BaseModel):
        """A property of a node in the event knowledge graph."""

        type: PropertyType = Field(  # type: ignore[valid-type]
            description=f"Type of the property. Must be one of {valid.classes}.",
        )
        value: str | int | float = Field(description="Extracted value of the property.")

    class Node(BaseModel):
        """A node in the event knowledge graph."""

        id: str = Field(description="Unique identifier for the node.")
        type: NodeType = Field(  # type: ignore[valid-type]
            description=f"Type of the node. Must be one of {valid.classes}.",
        )
        properties: list[Property] | None = Field(default=None, description="List of properties of the node.")

        __doc__ = (
            "A node in the event graph. "
            "Each node type has a specific set of allowed properties. "
            f"The allowed properties for each node type are: {valid.data_properties_schema} "
            f"The following structural relationships exist among node types: {valid.type_triples}."
        )

    class Relationship(BaseModel):
        """A relationship between two nodes in the event knowledge graph."""

        source_id: str = Field(description="Unique identifier of source node.")
        target_id: str = Field(description="Unique identifier of target node.")
        type: RelationshipType = Field(  # type: ignore[valid-type]
            description=f"Type of the relationship. Must be one of {valid.object_properties}.",
        )

        __doc__ = (
            "A relationship between two nodes in the event graph. "
            "Each relationship type has a predefined source and target node type. "
            "The allowed relationships, formatted as (source type, relationship type, target type), are: "
            f"{valid.object_property_triples}."
        )

    class EventGraph(BaseEventGraph):
        """An event knowledge graph composed of nodes and relationships."""

        nodes: list[Node] = Field(description="List of nodes in the graph.")
        relationships: list[Relationship] = Field(
            description="List of relationships in the graph.",
        )

        @model_validator(mode="after")
        def validate_relationships(self) -> "EventGraph":
            node_ids = {node.id for node in self.nodes}

            missing_nodes = {rel.source_id for rel in self.relationships if rel.source_id not in node_ids} | {
                rel.target_id for rel in self.relationships if rel.target_id not in node_ids
            }

            if missing_nodes:
                msg = "Relationships mention node ids that are not present in the nodes list: {missing_nodes}"
                err_type = "InvalidRelationships"
                raise PydanticCustomError(
                    err_type,
                    msg,
                    {"missing_nodes": missing_nodes},
                )

            return self

    return EventGraph
