"""Pydantic models for event graphs generated by the LLM."""

from enum import Enum

from langchain_neo4j.graphs.graph_document import GraphDocument
from langchain_neo4j.graphs.graph_document import Node as LibNode
from langchain_neo4j.graphs.graph_document import Relationship as LibRelationship
from pydantic import BaseModel, Field, model_validator
from pydantic_core import PydanticCustomError


class BaseEventGraph(BaseModel):
    """Base graph model to represent the graph generated by a LLM from a log event.

    Do not use this class directly in the llm's structured output:
    an ontology-specific subclass should be created using the `build_dynamic_model` function.
    """

    nodes: list
    relationships: list

    def graph(self) -> GraphDocument:
        """Convert the generated event graph to a GraphDocument.

        This method assumes that the nodes and relationships are already in the correct format,
        ontology-compliant, and with valid ids. As such, it does not perform any validation.
        """
        nodes_dict = {
            node.id: LibNode(
                id=node.id,
                type=node.type,
                properties={prop.type: prop.value for prop in node.properties} if node.properties else {},
            )
            for node in self.nodes
        }

        relationships = [
            LibRelationship(source=nodes_dict[rel.source_id], target=nodes_dict[rel.target_id], type=rel.type)
            for rel in self.relationships
        ]

        return GraphDocument(nodes=list(nodes_dict.values()), relationships=relationships)


def build_dynamic_model(ontology: GraphDocument) -> type[BaseEventGraph]:
    """Build a dynamic event graph model based on the ontology."""
    valid_node_types = [node.type for node in ontology.nodes]

    valid_relationship_types = [rel.type for rel in ontology.relationships]
    valid_triples = [(rel.source.type, rel.type, rel.target.type) for rel in ontology.relationships]

    valid_properties_per_node = {node.type: [*list(node.properties.keys()), "uri"] for node in ontology.nodes}
    valid_properties: list[str] = list({prop for props in valid_properties_per_node.values() for prop in props})
    valid_properties_schema = [f"{node}:{props}" for node, props in valid_properties_per_node.items()]

    NodeType = Enum("NodeType", {node: node for node in valid_node_types}, type=str)  # noqa: N806
    PropertyType = Enum("PropertyType", {prop: prop for prop in valid_properties}, type=str)  # noqa: N806
    RelationshipType = Enum("RelationshipType", {rel: rel for rel in valid_relationship_types}, type=str)  # noqa: N806

    # Note: The following class names clash with the ones from langchain_neo4j.
    # These names will be passed to the LLM, so it's (probably) better to keep them
    # as clearly named as possible and alias the ones from langchain_neo4j.

    class Property(BaseModel):
        """A property of a node in the event knowledge graph."""

        type: PropertyType = Field(  # type: ignore[valid-type]
            description=f"Type of the property. Must be one of: {valid_properties}",
        )
        value: str | int | float = Field(description="Extracted value of the property.")

    class Node(BaseModel):
        """A node in the event knowledge graph."""

        id: str = Field(description="Unique identifier for the node.")
        type: NodeType = Field(  # type: ignore[valid-type]
            description=f"Type of the node. Must be one of: {valid_node_types}",
        )
        properties: list[Property] | None = Field(default=None, description="List of properties of the node.")

        __doc__ = (
            "A node in the event graph. "
            "Each node type has a specific set of allowed properties. "
            f"The allowed properties for each node type are: {valid_properties_schema} "
        )

    class Relationship(BaseModel):
        """A relationship between two nodes in the event knowledge graph."""

        source_id: str = Field(description="Unique identifier of source node.")
        target_id: str = Field(description="Unique identifier of target node.")
        type: RelationshipType = Field(  # type: ignore[valid-type]
            description=f"Type of the relationship. Must be one of: {valid_relationship_types}",
        )

        __doc__ = (
            "A relationship between two nodes in the event graph. "
            "Each relationship type has a predefined source and target node type. "
            "The allowed relationships, formatted as (source type, relationship type, target type), are: "
            f"{valid_triples}."
        )

    class EventGraph(BaseEventGraph):
        """An event knowledge graph composed of nodes and relationships."""

        nodes: list[Node] = Field(description="List of nodes in the graph.")
        relationships: list[Relationship] = Field(
            description="List of relationships in the graph.",
        )

        @model_validator(mode="after")
        def validate_relationships(self) -> "EventGraph":
            node_ids = {node.id for node in self.nodes}

            missing_nodes = {rel.source_id for rel in self.relationships if rel.source_id not in node_ids} | {
                rel.target_id for rel in self.relationships if rel.target_id not in node_ids
            }

            if missing_nodes:
                msg = "Relationships mention node ids that are not present in the nodes list: {missing_nodes}"
                raise PydanticCustomError(
                    error_type="InvalidRelationships",
                    message_template=msg,
                    context={"missing_nodes": missing_nodes},
                )

            return self

    return EventGraph
