"""Pydantic models for event graphs generated by the LLM."""

from enum import Enum

from langchain_neo4j.graphs.graph_document import GraphDocument
from langchain_neo4j.graphs.graph_document import Node as LibNode
from langchain_neo4j.graphs.graph_document import Relationship as LibRelationship
from pydantic import BaseModel, Field, model_validator
from pydantic_core import PydanticCustomError


class BaseEventGraph(BaseModel):
    """Base graph model to represent the graph generated by a LLM from a log event.

    Do not use this class directly in the llm's structured output:
    an ontology-specific subclass should be created using the `build_dynamic_model` function.
    """

    nodes: list
    relationships: list

    def graph(self) -> GraphDocument:
        """Convert the generated event graph to a GraphDocument.

        This method assumes that the nodes and relationships are already in the correct format,
        ontology-compliant, and with valid ids. As such, it does not perform any validation.
        """
        nodes_dict = {
            node.id: LibNode(
                id=node.id,
                type=node.type,
                properties={prop.type: prop.value for prop in node.properties} if node.properties else {},
            )
            for node in self.nodes
        }

        relationships = [
            LibRelationship(source=nodes_dict[rel.source_id], target=nodes_dict[rel.target_id], type=rel.type)
            for rel in self.relationships
        ]

        return GraphDocument(nodes=list(nodes_dict.values()), relationships=relationships)


class _OntologyValidValues:
    """Class to hold the valid values for the ontology."""

    def __init__(self, ontology: GraphDocument):
        self.ontology = ontology

    @property
    def node_types(self) -> list[str]:
        return [node.type for node in self.ontology.nodes]

    @property
    def relationship_types(self) -> list[str]:
        return [rel.type for rel in self.ontology.relationships]

    @property
    def triples(self) -> list[tuple[str, str, str]]:
        return [(rel.source.type, rel.type, rel.target.type) for rel in self.ontology.relationships]

    @property
    def properties_per_node(self) -> dict[str, list[str]]:
        return {node.type: [*list(node.properties.keys()), "uri"] for node in self.ontology.nodes}

    @property
    def properties(self) -> list[str]:
        return list({prop for props in self.properties_per_node.values() for prop in props})

    @property
    def properties_schema(self) -> list[str]:
        return [f"{node}:{props}" for node, props in self.properties_per_node.items()]


def build_dynamic_model(ontology: GraphDocument) -> type[BaseEventGraph]:
    """Build a dynamic event graph model based on the ontology."""
    valid = _OntologyValidValues(ontology)

    NodeType = Enum("NodeType", {node: node for node in valid.node_types}, type=str)  # noqa: N806
    PropertyType = Enum("PropertyType", {prop: prop for prop in valid.properties}, type=str)  # noqa: N806
    RelationshipType = Enum("RelationshipType", {rel: rel for rel in valid.relationship_types}, type=str)  # noqa: N806

    # Note: The following class names clash with the ones from langchain_neo4j.
    # These names will be passed to the LLM, so it's (probably) better to keep them
    # as clearly named as possible and alias the ones from langchain_neo4j.

    class Property(BaseModel):
        """A property of a node in the event knowledge graph."""

        type: PropertyType = Field(  # type: ignore[valid-type]
            description="Type of the property.",
        )
        value: str | int | float = Field(description="Extracted value of the property.")

    class Node(BaseModel):
        """A node in the event knowledge graph."""

        id: str = Field(description="Unique identifier for the node.")
        type: NodeType = Field(  # type: ignore[valid-type]
            description="Type of the node.",
        )
        properties: list[Property] | None = Field(default=None, description="List of properties of the node.")

        __doc__ = (
            "A node in the event graph. "
            "Each node type has a specific set of allowed properties. "
            f"The allowed properties for each node type are: {valid.properties_schema} "
        )

    class Relationship(BaseModel):
        """A relationship between two nodes in the event knowledge graph."""

        source_id: str = Field(description="Unique identifier of source node.")
        target_id: str = Field(description="Unique identifier of target node.")
        type: RelationshipType = Field(  # type: ignore[valid-type]
            description="Type of the relationship.",
        )

        __doc__ = (
            "A relationship between two nodes in the event graph. "
            "Each relationship type has a predefined source and target node type. "
            "The allowed relationships, formatted as (source type, relationship type, target type), are: "
            f"{valid.triples}."
        )

    class EventGraph(BaseEventGraph):
        """An event knowledge graph composed of nodes and relationships."""

        nodes: list[Node] = Field(description="List of nodes in the graph.")
        relationships: list[Relationship] = Field(
            description="List of relationships in the graph.",
        )

        @model_validator(mode="after")
        def validate_relationships(self) -> "EventGraph":
            node_ids = {node.id for node in self.nodes}

            missing_nodes = {rel.source_id for rel in self.relationships if rel.source_id not in node_ids} | {
                rel.target_id for rel in self.relationships if rel.target_id not in node_ids
            }

            if missing_nodes:
                msg = "Relationships mention node ids that are not present in the nodes list: {missing_nodes}"
                err_type = "InvalidRelationships"
                raise PydanticCustomError(
                    err_type,
                    msg,
                    {"missing_nodes": missing_nodes},
                )

            return self

        @model_validator(mode="after")
        def validate_event(self) -> "EventGraph":
            """Validate the event graph.

            This method is a placeholder for any additional validation logic that may be needed.
            """
            event_nodes = [node for node in self.nodes if node.type == "Event"]
            if len(event_nodes) != 1:
                msg = "The event graph must contain exactly one 'Event' node."
                err_type = "IncorrectEventNodes"
                raise PydanticCustomError(err_type, msg)

            event_node = event_nodes[0]
            if not event_node.properties or not any(prop.type == "eventMessage" for prop in event_node.properties):
                msg = "The 'Event' node must have a property of type 'eventMessage'."
                err_type = "MissingEventProperty"
                raise PydanticCustomError(err_type, msg)

            return self

    return EventGraph


def build_baseline_prompt(ontology: GraphDocument, base_prompt: str) -> str:
    """Build a baseline prompt for the LLM to generate an event graph."""
    valid = _OntologyValidValues(ontology)

    prompt = base_prompt.replace("{{node_types}}", str(valid.node_types))
    prompt = prompt.replace("{{relationship_types}}", str(valid.relationship_types))
    prompt = prompt.replace("{{properties}}", str(valid.properties))
    prompt = prompt.replace("{{properties_schema}}", str(valid.properties_schema))
    return prompt.replace("{{triples}}", str(valid.triples))
