services:
  embs:
    image: michaelf34/infinity:0.0.77
    container_name: ${EXPERIMENT_NAME:-default}_embs
    volumes:
      - ${PWD}/exps/${EXPERIMENT_NAME:-default}/embs:/app/.cache
    restart: on-failure:3
    runtime: nvidia
    command: v2 --model-id ${EMBEDDINGS_MODEL} --dtype float16 --port 9000
    networks:
      - ontologx
    expose:
      - 9000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9000/docs"]
      interval: 20s
      timeout: 10s
      retries: 30
      start_period: 30s
      start_interval: 10s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  graphdb:
    image: ontotext/graphdb:11.2.0
    container_name: ${EXPERIMENT_NAME:-default}_graphdb
    volumes:
      - ${PWD}/resources/graphdb/graphdb.license:/opt/graphdb/home/conf/graphdb.license
    networks:
      - ontologx
    expose:
      - 7200
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:7200"]
      interval: 20s
      timeout: 10s
      retries: 30
      start_period: 30s
      start_interval: 10s

networks:
  ontologx:
    driver: bridge
