name: ${EXPERIMENT_NAME:-default}
include:
  - common.yaml

services:
  ontologx:
    build:
      context: ..
      dockerfile: docker/ontologx.dockerfile
    container_name: ${EXPERIMENT_NAME:-default}_olx
    environment:
      - LLM_BACKEND=bedrock
      - EMBEDDINGS_BACKEND=infinity
      - EMBEDDINGS_BACKEND_URL=http://embs:9000
      - DB_URL=http://graphdb:7200/repositories/ontologx
      - OPENAI_API_KEY=Empty # Required by OpenAI client API
    env_file:
      - ${PWD}/.env
    depends_on:
      embs:
        condition: service_healthy
        restart: true
      graphdb:
        condition: service_healthy
        restart: true
    networks:
      - ontologx
