name: ${EXPERIMENT_NAME:-default}
include:
  - common.yaml

services:
  ontologx:
    build:
      context: ..
      dockerfile: docker/ontologx.dockerfile
    container_name: ${EXPERIMENT_NAME:-default}_olx
    environment:
      - PARSER_BACKEND=bedrock
      - EMBEDDINGS_BACKEND=infinity
      - EMBEDDINGS_BACKEND_URL=http://embs:9000
      - TACTICS_BACKEND=openai
      - TACTICS_BACKEND_URL=http://tactics:8000/v1
      - GEVAL_BACKEND=bedrock
      - NEO4J_URL=bolt://neo4j:7687
    env_file:
      - ${PWD}/.env
    depends_on:
      embs:
        condition: service_healthy
        restart: true
      neo4j:
        condition: service_healthy
        restart: true
    networks:
      - ontologx
