services:
  ontologx:
    build:
      context: ..
      dockerfile: docker/ontologx.dockerfile
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME}-ontologx
    environment:
      - LLM_BACKEND=vllm
      - LLM_BACKEND_URL=http://llm:8000
      - EMBEDDINGS_BACKEND=vllm
      - EMBEDDINGS_BACKEND_URL=http://embeddings:8000
      - NEO4J_URL=bolt://neo4j:7687
    depends_on:
      llm:
        condition: service_healthy
        restart: true
      embeddings:
        condition: service_healthy
        restart: true
      neo4j:
        condition: service_healthy
        restart: true
    networks:
      - ontologx-docker

  llm:
    image: vllm/vllm-openai:v0.8.5
    container_name: ${COMPOSE_PROJECT_NAME}-ontologx-llm
    volumes:
      - .vllm/llms:/root/.cache/huggingface # Models permanence
    runtime: nvidia
    ipc: host # Allow the container access to the host's shared memory
    restart: unless-stopped
    networks:
      - ontologx-docker
    entrypoint: python3
    command: -m vllm.entrypoints.openai.api_server --model ${PARSER_MODEL} --trust-remote-code
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  embeddings:
    image: vllm/vllm-openai:v0.8.5
    container_name: ${COMPOSE_PROJECT_NAME}-ontologx-embeddings
    volumes:
      - .vllm/embeddings:/root/.cache/huggingface # Models permanence
    runtime: nvidia
    ipc: host # Allow the container access to the host's shared memory
    restart: unless-stopped
    networks:
      - ontologx-docker
    entrypoint: python3
    command: -m vllm.entrypoints.openai.api_server --model ${EMBEDDINGS_MODEL} --task embed --trust-remote-code
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  neo4j:
    build:
      context: .
      dockerfile: neo4j.dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-ontologx-neo4j
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    networks:
      - ontologx-docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 3s

networks:
  ontologx-docker:
    driver: bridge
