name: ontologx-vllm

services:
  ontologx:
    build:
      context: ..
      dockerfile: docker/ontologx.dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-default}_olx
    environment:
      - LLM_BACKEND=vllm
      - LLM_BACKEND_URL=http://llm:8000/v1
      - EMBEDDINGS_BACKEND=infinity
      - EMBEDDINGS_BACKEND_URL=http://embs:9000
      - TESTS_BACKEND=bedrock
      - NEO4J_URL=bolt://neo4j:7687
      - OPENAI_API_KEY=Empty # Required by OpenAI client API
      - TRANSFORMERS_VERBOSITY=critical
    env_file:
      - ../.env
    depends_on:
      llm:
        condition: service_healthy
        restart: true
      embs:
        condition: service_healthy
        restart: true
      neo4j:
        condition: service_healthy
        restart: true
    networks:
      - ontologx

  llm:
    image: vllm/vllm-openai:v0.9.0
    container_name: ${COMPOSE_PROJECT_NAME:-default}_llm
    volumes:
      - .exps/${COMPOSE_PROJECT_NAME:-default}/vllm/llms:/root/.cache/huggingface # Save models so they are not downloaded every time
    runtime: nvidia
    ipc: host # Allow the container access to the host's shared memory
    restart: on-failure:3
    expose:
      - 8000
    networks:
      - ontologx
    entrypoint: python3
    command: -m vllm.entrypoints.openai.api_server --model ${LLM_MODEL} --task generate --trust-remote-code ${VLLM_ADDITIONAL_ARGS-} # Ad-hoc vllm arguments are likely to be needed
    environment:
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - CUDA_VISIBLE_DEVICES=${VLLM_VISIBLE_DEVICES-}
    env_file:
      - ../.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 20s
      timeout: 10s
      retries: 300 # A lot of retries because big models may take a while to load
      start_period: 30s
      start_interval: 10s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  embs:
    image: michaelf34/infinity:0.0.76
    container_name: ${COMPOSE_PROJECT_NAME:-default}_embs
    volumes:
      - .exps/${COMPOSE_PROJECT_NAME:-default}/embs:/app/.cache
    restart: on-failure:3
    runtime: nvidia
    command: v2 --model-id ${EMBEDDINGS_MODEL} --dtype float16 --port 9000
    networks:
      - ontologx
    expose:
      - 9000
    env_file:
      - ../.env
    environment:
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - CUDA_VISIBLE_DEVICES=${INFINITY_VISIBLE_DEVICES-}
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:9000/docs" ]
      interval: 20s
      timeout: 10s
      retries: 30
      start_period: 30s
      start_interval: 10s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

  neo4j:
    image: neo4j:5.20.0
    container_name: ${COMPOSE_PROJECT_NAME:-default}_neo4j
    environment:
      - NEO4J_PLUGINS=["apoc", "n10s"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,n10s.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,n10s.*
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - .exps/${COMPOSE_PROJECT_NAME:-default}/neo4j/data:/data
      - .exps/${COMPOSE_PROJECT_NAME:-default}/neo4j/logs:/logs
      - .exps/${COMPOSE_PROJECT_NAME:-default}/neo4j/plugins:/plugins
    networks:
      - ontologx
    expose:
      - 7474
      - 7687
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:7474" ] # The neo4j image has wget only, not curl
      interval: 20s
      timeout: 10s
      retries: 30
      start_period: 30s
      start_interval: 10s

networks:
  ontologx:
    driver: bridge
